"""change duration type to Float in n Goal table

Revision ID: 233a72b6c961
Revises: 6136882b01d1
Create Date: 2025-05-08 11:29:19.502239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233a72b6c961'
down_revision = '6136882b01d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_session', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.DATETIME(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_session', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.Float(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
