"""remove activity_type_id in Goal

Revision ID: 6136882b01d1
Revises: 5db58d0a9c69
Create Date: 2025-05-08 11:05:56.994426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6136882b01d1'
down_revision = '5db58d0a9c69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_constraint('fk_goal_activity_type_id_activity_type', type_='foreignkey')
        batch_op.drop_column('activity_type_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_type_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_goal_activity_type_id_activity_type', 'activity_type', ['activity_type_id'], ['id'])

    # ### end Alembic commands ###
