"""init all table

Revision ID: 676e91a9f80c
Revises: 7989e48898a0
Create Date: 2025-05-14 17:01:36.046356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676e91a9f80c'
down_revision = '7989e48898a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shared_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shared_user_id'], ['user.id'], name=op.f('fk_share_user_shared_user_id_user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_share_user_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('name')

    op.drop_table('share_user')
    # ### end Alembic commands ###
