"""add new features fofinished_at, actual_duration_finised,actual_reps_finished for activitysessision table

Revision ID: 79378e50c2c2
Revises: f58288ef5306
Create Date: 2025-05-11 11:55:22.138730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79378e50c2c2'
down_revision = 'f58288ef5306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finished_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('actual_duration_finished', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('actual_reps_finished', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_session', schema=None) as batch_op:
        batch_op.drop_column('actual_reps_finished')
        batch_op.drop_column('actual_duration_finished')
        batch_op.drop_column('finished_at')

    # ### end Alembic commands ###
