"""add new table ActivityRecord to record activitysession

Revision ID: 7989e48898a0
Revises: 79378e50c2c2
Create Date: 2025-05-11 12:11:05.805176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7989e48898a0'
down_revision = '79378e50c2c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('actual_duration', sa.Float(), nullable=True),
    sa.Column('actual_reps', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['activity_session.id'], name=op.f('fk_activity_record_session_id_activity_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_record'))
    )
    with op.batch_alter_table('activity_session', schema=None) as batch_op:
        batch_op.drop_column('actual_duration_finished')
        batch_op.drop_column('actual_reps_finished')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_reps_finished', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('actual_duration_finished', sa.FLOAT(), nullable=True))

    op.drop_table('activity_record')
    # ### end Alembic commands ###
