"""chset target value nullable

Revision ID: f58288ef5306
Revises: 233a72b6c961
Create Date: 2025-05-08 12:36:57.918394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58288ef5306'
down_revision = '233a72b6c961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.alter_column('target_value',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.alter_column('target_value',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
